### ISSUE TITLE
Nested folder usage?

### ISSUE THREAD

**Issue by ap1969** [opentable/spur-ioc#39]
Hi,
I've got IOC working with a one-level folder structure:

./injector.js 
./routes/resource.js
./routes/admin.js

This works great - so first: thanks for the hard work on this.

However, I'd like to add a second level:

./routes/mobile/<route1>.js
./routes/mobile/<route2>.js

But I can't find a way to get this working. Is it even possible? If so, could you provide an example please?

Regards,
Andy

**Comment by ap1969** [comment]
Sorry, should have clarified that I'm using:

```
ioc.registerFolders(__dirname, [
    "routes"
  ]);
```
And it doesn't seem to pick up the subfolder.

Regards,
Andy

**Comment by ap1969** [comment]
Actually, I'm just reviewing source code. Would I simply have to do the following?

```
ioc.registerFolders(__dirname, [
    "routes",
    "routes/mobile"
  ]);
```

**Comment by ap1969** [comment]
OK, further digging, and it looks like you're using node module require-all, which has an optional recursive option which isn't being used in Spur IOC. I'll try my own suggestion in the last of my frantic updates and get back with details for future reference.

**Comment by ap1969** [comment]
I'm back - done some further investigation. I'm not sure it's an IOC issue. The file is picked up in the nested folder and included in a list of dependent object that I display in a debug statement. I can also at that point call a method on the object and it returns the correct response. The only issue is when I use that object in ExpressJS, so I don't think it's an issue with IOC, as other objects are working fine in Express.

If it does turn out to be an IOC issue, I'll come back and share details, and try to create a test case.

**Comment by acolchado** [comment]
@Notifium Sorry for the delay, missed the notification for this. I will review the details above and see if anything has broken due to a recent change in a dependency. We are using it in the way you describe, even as far as 4-5 levels (don't ask).

Your original example is the correct usage: 

```
ioc.registerFolders(__dirname, [
    "routes",
  ]);
```

Could you please provide more details about the environment you're running on. Operating system and version, node and npm version would help.

I will add a unit test to verify that this continues to work.

Thanks!
